language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: npm
  email: jeremy@tenfourty.com
  api_key:
    secure: LgEq3OMb0KVJXMJUfbTyyueHIdDFMAzOmtlK8bKELbOYJY+eD//hr5IXZgaZGxhVFaQZVNZi93+HJyiCFAHyhYXqQhBgdnmY8hjlmf5U4jY/w8ma3M/JRFOvpDiZVpnOX/LkQjWNqsW3JL34aTba4egK4bbaRBN93Y9A8tBFNlySq8w/maEbF58M6iUq2wALRr0cUzA8d7+e7mcNwvhqw68xZKa/1ASwFKSC+8j3QiU07PxOly1GJsLK3Gk7X4ebbYizsZtEWsqmbyxTNdnXRp0cZ9x/s1s7T1e0GdEFZ5bhd2IqPxXZRwd5TTUOhvKOy73AUIeHz3OVWK1ID9p4hqC07UHybGaPQCpuRSTvGTvmhtbCUExTSGJRbG/VQf8lx4zqJE/uoUW7Y0KmVc82ROycm+xMn81nsf1OFq2RLFjQw5NK+Jr+1v1YngDLhDsJm9YCkiiFKTnHSveaRxb75xT8Yb7dWcwRhcx9z+ybrGPiJlyDfdNqwqy9d/TpLyGEwPKqe0pDkWiOeqB2dHZo0wVkkjJZ8e4WblMDCSvk75FihE2GPFxYjsobTf2Cr7BX+/ENkTnR3HgkzR6/KPzcdTzm9TCrDV8EfYj57n6kdT/uKhjvCFez8P+5WZLua8aa80dIUTWtPb72ylzWPE9ABhsNn3KgvKqjdAarrDsgI2U=
  on:
    repo: tenfourty/hubot-counter
